from .author_response_docs import (
    AUTHOR_SUCCESS_RESPONSE,
    AUTHOR_NOT_FOUND_RESPONSE,
    ALL_AUTHORS_SUCCESS_RESPONSE
)

from .user_response_docs import (
    USER_SUCCESS_RESPONSE,
    USER_NOT_FOUND_RESPONSE,
    FORBIDDEN_RESPONSE,
    USER_SEARCH_RESPONSES,
    USER_BAD_REQUEST,
    USER_UNAUTHORIZED
)