version: "3.9"

services:
  bookland:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bookland
    env_file:
      - backend/.env
    volumes:
      - .:/home/devuser/app
    ports:
      - "8080:8080"
    networks:
      - network_app
    command: uvicorn bookland.api.main:app --host 0.0.0.0 --port 8080 --reload

networks:
  network_app:
    driver: bridge
