version: "3.9"

services:
  bookland:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bookland
    env_file:
      - backend/.env
    volumes:
      - .:/home/devuser/app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    command: uvicorn bookland.api.main:app --host 0.0.0.0 --port 8080 --reload
    networks:
      - network_app

  mongo:
    image: mongo:7
    restart: unless-stopped
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - network_app

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - "${MONGOEXPRESS_PORT}:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_BASICAUTH_PASSWORD}
    depends_on:
      - mongo
    networks:
      - network_app

volumes:
  mongo_data:

networks:
  network_app:
    driver: bridge
