from .birthdate_vo import BirthDate
from .date_vo import Date
from .email_vo import Email
from .isbn_vo import Isbn
from .label_vo import Label
from .name_vo import Name
from .nickname_vo import Nickname
from .password_vo import Password
from .rating_vo import Rating
from .reading_criteria_vo import ReadingCriteria
from .slug_vo import Slug
from .title_vo import Title
