from .author_mapper import AuthorMapper
from .book_mapper import BookMapper
from .bookshelf_mapper import BookshelfMapper
from .criterion_mapper import CriterionMapper
from .genre_mapper import GenreMapper
from .reading_in_progress_mapper import ReadingInProgressMapper
from .review_mapper import ReviewMapper
from .series_mapper import SeriesMapper
from .trope_mapper import TropeMapper
from .user_mapper import UserMapper
from .user_book_mapper import UserBookMapper
